Reorganised the script for converting the lexicon to IPA to be able to handle multiple conversions depending on the orthography of the stem.

diff --git a/tools/shellscripts/generate-ipa-lexicon.sh.in b/tools/shellscripts/generate-ipa-lexicon.sh.in
--- a/tools/shellscripts/generate-ipa-lexicon.sh.in
+++ b/tools/shellscripts/generate-ipa-lexicon.sh.in
@@ -14,6 +14,9 @@
 
 ###### Variables: #######
 
+# Languages:
+languages="sme fin"
+
 # $srcdir:
 if test -z "$srcdir"; then
     srcdir=$(echo "$0" | sed s,[^/]*$,,)
@@ -22,47 +25,53 @@ if test -z "$srcdir"; then
 fi
 
 # Fst files:
-generator=${srcdir}/../../src/generator-tts-gt-norm_nonum_noabbr_nohyph.hfst
 hyphenator=${srcdir}/../../src/hyphenation/hyphenation.hfst
-ipa_converter=${srcdir}/../../src/phonetics/text2ipa.hfst
-
-# Output file:
-tts_lexicon=${srcdir}/tts-lexicon.txt
 
 # Check whether the actual fst's exist:
-if ! test -f "$generator" ; then
-    echo "FAIL: Transducer not found! $generator"
-    exit 1
-fi
 if ! test -f "$hyphenator" ; then
     echo "FAIL: Transducer not found! $hyphenator"
-    exit 1
-fi
-if ! test -f "$ipa_converter" ; then
-    echo "FAIL: Transducer not found! $ipa_converter"
     exit 1
 fi
 
 hfst_lookup="@HFST_LOOKUP@"
 hfst_fst2strings=@HFST_FST2STRINGS@
 
-$hfst_fst2strings $generator --random=2000 > $tts_lexicon.tmp.txt
-# Extract word forms:
-cut -d':' -f 2- < $tts_lexicon.tmp.txt > $tts_lexicon.wordforms.txt
-# Extract lemmas:
-cut -d':' -f 1 < $tts_lexicon.tmp.txt > $tts_lexicon.lemmas.txt
-# Convert word forms to IPA:
-$hfst_lookup -q $hyphenator < $tts_lexicon.wordforms.txt \
-    | cut -f2 \
-    | grep -v '^$' \
-    | $hfst_lookup -q $ipa_converter \
-    > $tts_lexicon.ipatmp.txt
-# Remove empty lines (done separately to preserve easy identification of
-# double IPA conversion/overgeneration, in the ipatmp file):
-grep -v '^$' < $tts_lexicon.ipatmp.txt > $tts_lexicon.ipa.txt
-tr -d "#^»>" < $tts_lexicon.wordforms.txt > $tts_lexicon.wordformsclean.txt
-paste $tts_lexicon.lemmas.txt \
-      $tts_lexicon.wordformsclean.txt \
-      $tts_lexicon.ipa.txt \
-    | cut -f1,2,4 \
-    > $tts_lexicon
+for lang in $languages; do
+    # Fst files:
+    generator=${srcdir}/../../src/generator-tts-gt-norm_nonum_noabbr_nohyph_$lang.hfst
+    ipa_converter=${srcdir}/../../src/phonetics/text2ipa-$lang.hfst
+    
+    # Output file:
+    tts_lexicon=${srcdir}/tts-lexicon-$lang.txt
+    
+    # Check whether the actual fst's exist:
+    if ! test -f "$generator" ; then
+        echo "FAIL: Transducer not found! $generator"
+        exit 1
+    fi
+    if ! test -f "$ipa_converter" ; then
+        echo "FAIL: Transducer not found! $ipa_converter"
+        exit 1
+    fi
+    
+	$hfst_fst2strings $generator --random=2000 > $tts_lexicon.tmp.txt
+	# Extract word forms:
+	cut -d':' -f 2- < $tts_lexicon.tmp.txt > $tts_lexicon.wordforms.txt
+	# Extract lemmas:
+	cut -d':' -f 1 < $tts_lexicon.tmp.txt > $tts_lexicon.lemmas.txt
+	# Convert word forms to IPA:
+	$hfst_lookup -q $hyphenator < $tts_lexicon.wordforms.txt \
+	    | cut -f2 \
+	    | grep -v '^$' \
+	    | $hfst_lookup -q $ipa_converter \
+	    > $tts_lexicon.ipatmp.txt
+	# Remove empty lines (done separately to preserve easy identification of
+	# double IPA conversion/overgeneration, in the ipatmp file):
+	grep -v '^$' < $tts_lexicon.ipatmp.txt > $tts_lexicon.ipa.txt
+	tr -d "#^»>" < $tts_lexicon.wordforms.txt > $tts_lexicon.wordformsclean.txt
+	paste $tts_lexicon.lemmas.txt \
+	      $tts_lexicon.wordformsclean.txt \
+	      $tts_lexicon.ipa.txt \
+	    | cut -f1,2,4 \
+	    > $tts_lexicon
+done
