[Template merge] giellaltlextools lemma testing

diff --git a/src/fst/morphology/test/generate-noun-lemmas.sh.in b/src/fst/morphology/test/generate-noun-lemmas.sh.in
--- a/src/fst/morphology/test/generate-noun-lemmas.sh.in
+++ b/src/fst/morphology/test/generate-noun-lemmas.sh.in
@@ -14,8 +14,7 @@ exclusions="--exclude (CmpN/Only|ShCmp|\+Cmp/SplitR|\+V\+|AGAdj|AHKASAS|NOT-TO-L
 # avoid changing common scripting stuff here:
 
 . "$GIELLA_CORE/scripts/termcolors.bash"
-PYTHON=@PYTHON@
-genscript=$GIELLA_CORE/scripts/generate-lemmas.py
+genscript=@GTLEMMATEST@
 
 # ensure this is proper run from make check or otherwise set up
 if test -z "$srcdir" ; then
@@ -24,9 +23,9 @@ if test -z "$srcdir" ; then
     exit 1
 fi
 if ! test -f "$genscript" ; then
-    printf "%sfail%s missing generator script %s\n" "$red" "$reset" \
+    printf "%sskip%s missing generator script %s\n" "$light_blue" "$reset" \
         "$genscript"
-    exit 1
+    exit 77
 fi
 if ! test -f "$generator_file.hfstol" ; then
     printf "%sfail%s missing generator FSA %s.hfstol\n" "$red" "$reset" \
@@ -39,7 +38,7 @@ if ! test -f "$analyser_file.hfstol" ; then
     exit 1
 fi
 
-"$PYTHON" -- "$genscript" -l "$source_file" \
+"$genscript" -l "$source_file" \
     -g "$generator_file.hfstol" -a "$analyser_file.hfstol" \
     -t "$tags" $xtags $inclusions $exclusions
 rv=$?
