[Template merge] python generate lemmas

diff --git a/src/fst/morphology/test/generate-propernoun-lemmas.sh.in b/src/fst/morphology/test/generate-propernoun-lemmas.sh.in
--- a/src/fst/morphology/test/generate-propernoun-lemmas.sh.in
+++ b/src/fst/morphology/test/generate-propernoun-lemmas.sh.in
@@ -1,173 +1,56 @@
 #!/bin/bash
-# @configure_input@
-
-# Automake interprets the exit status as follows:
-# - an exit status of 0 will denote a success
-# - an exit status of 77 a skipped test
-# - an exit status of 99 a hard error
-# - any other exit status will denote a failure.
-
-# To run this test script only, do:
+# Test script for proper noun lemma generation
 #
-# make check TESTS=generate-propernoun-lemmas.sh
-
-# This test script will test that all propernoun lemmas do generate as themselves.
-# Extend as needed, and copy to new files to adapt to other parts of speech.
-# The changes usually needed are:
-#
-# 1. change the reference to the source file (line 23)
-# 2. extend the extract lemmas egrep expression (lines 53 ff)
-# 3. adapt the tag addition and lemma generation instructions (lines 79 ff)
-
-###### Variables: #######
+# change settings here:
 POS=propernouns
-### in ###
-source_file=./../generated_files/smi-sme-${POS}.lexc
-generator_file=./../../generator-gt-norm
-analyser_file=./../../analyser-gt-norm
+source_file=@abs_srcdir@/../stems/${POS}.lexc
+generator_file=@abs_builddir@/../../generator-gt-norm
+analyser_file=@abs_builddir@/../../analyser-gt-norm
+tags="+N+Prop+Sg+Nom"
+# advanced settings (leave empty or write full args)
+xtags="-t +N+Prop+Sg+Nom -t +N+Prop+Attr"
+inclusions=
+exclusions="--exclude (ProperNoun|\+Use/MT)"
+# avoid changing common sritping stuff here:
 
-### out ###
-# Temporary files:
-lemmas=./filtered-${POS}.txt
-# Result files, will get filename suffix programmatically further down:
-generated_lemmas=./generated-${POS}
-generated_lemmas_sgnom=./generated-${POS}-sgnom
-generated_lemmas_plnom=./generated-${POS}-plnom
-generated_lemmas_attr=./generated-${POS}-attr
-result_file=missing_${POS}_lemmas
-gen_result_file=generated_missing_${POS}_lemmas
-ana_result_file=analysed_missing_${POS}_lemmas
+. "$GIELLA_CORE/scripts/termcolors.bash"
+PYTHON=@PYTHON@
+genscript=$GIELLA_CORE/scripts/generate-lemmas.py
 
-# SKIP if source file does not exist (works with both single and
-# multiple files):
-if [ ! `ls -1 $source_file 2>/dev/null | wc -l ` -gt 0 ]; then
-    echo
-    echo "*** Warning: Source file(s) $source_file not found."
-    echo
+# ensure this is proper run from make check or otherwise set up
+if test -z "$srcdir" ; then
+    printf "%sfail%s %s needs to run from make check or set srcdir=.\n" \
+        "$red" "$reset" "$0"
+    exit 1
+fi
+if ! test -f "$genscript" ; then
+    printf "%sfail%s missing generator script %s\n" "$red" "$reset" \
+        "$genscript"
+    exit 1
+fi
+if ! test -f "$generator_file.hfstol" ; then
+    printf "%sfail%s missing generator FSA %s.hfstol\n" "$red" "$reset" \
+        "$generator_file"
+    exit 1
+fi
+if ! test -f "$analyser_file.hfstol" ; then
+    printf "%sfail%s missing analyser FSA %s.hfstol\n" "$red" "$reset" \
+        "$analyser_file"
+    exit 1
+fi
+if ! test -f "$source_file" ; then
+    printf "%sfail%s missing lexc file %s\n" "$red" "$reset" \
+        "$source_file"
+fi
+
+"$PYTHON" -- "$genscript" -l "$source_file" \
+    -g "$generator_file.hfstol" -a "$analyser_file.hfstol" \
+        -t "$tags" $xtags $inclusions $exclusions
+rv=$?
+if test $rv = 77 ; then
+    printf "%sskipped%s" "$light_blue" "$reset"
     exit 77
+elif test $rv -gt 0 ; then
+    printf "%sfailed%s" "$red" "$reset"
+    exit 1
 fi
-
-# Use autotools mechanisms to only run the configured fst types in the tests:
-fsttype=
-@CAN_HFST_TRUE@fsttype="$fsttype hfst"
-@CAN_XFST_TRUE@fsttype="$fsttype xfst"
-
-# Exit if both hfst and xerox have been shut off:
-if test -z "$fsttype" ; then
-    echo "All transducer types have been shut off at configure time."
-    echo "Nothing to test. Skipping."
-    exit 77
-fi
-
-# Get external Mac editor for viewing failed results from configure:
-EXTEDITOR=@SEE@
-
-##### Extract lemmas - add additional egrep pattern as parameters: #####
-##### --include "(pattern1|pattern2|...)"                          #####
-##### --exclude "(pattern1|pattern2|...)"                          #####
-
-# Hent ut lemmaer fra den genererte fila smi-sme-propernouns.lexc, bortsett fra utkommmenterte (^\!) og
-# Err/Lex (som blir filtrert bort fra normgenerator).
-# Lemmaene lagres som $lemmas.
-@GTCORE@/scripts/extract-lemmas.sh \
-    --exclude "(ProperNoun|\+Use/MT)" \
-    $source_file > $lemmas
-
-###### Start testing: #######
-transducer_found=0
-Fail=0
-
-# The script tests both Xerox and Hfst transducers if available:
-for f in $fsttype; do
-    if [ $f == "xfst" ]; then
-        lookup_tool="@LOOKUP@ -flags mbTT"
-        suffix="xfst"
-        # Does lookup support -q / quiet mode?
-        lookup_quiet=$($lookup_tool -q 2>&1 | grep USAGES)
-        if ! [[ $lookup_quiet == *"USAGES"* ]] ; then
-            # it does support quiet mode, add the -q flag:
-            lookup_tool="@LOOKUP@ -q -flags mbTT"
-        fi
-    elif [ $f == "hfst" ]; then
-        lookup_tool="@HFST_OPTIMIZED_LOOKUP@ -q"
-        suffix="hfstol"
-    else
-        Fail=1
-        printf "ERROR: Unknown fst type! "
-        echo "$f - FAIL"
-        continue
-    fi
-    if [ -f "$generator_file.$suffix" ]; then
-        let "transducer_found += 1"
-
-###### Test generation: #######
-		# generate verbs, extract the resulting generated lemma,
-		# store it:
-
-# Generer grunnformen av props med +N+Prop+Sg+Nom
-		sed 's/$/+N+Prop+Sg+Nom/' $lemmas \
-			| $lookup_tool $generator_file.$suffix \
-			| cut -f2 > $generated_lemmas_sgnom.$f.txt
-
-# Ta dei som ikkje vart generert og generer dei med +N+Prop+Pl+Nom
-		grep "+N" $generated_lemmas_sgnom.$f.txt | sed 's/+N+Prop+Sg+Nom/+N+Prop+Pl+Nom/' \
-			| $lookup_tool $generator_file.$suffix \
-			| cut -f2 > $generated_lemmas_plnom.$f.txt
-
-# Ta dei som framleis ikkje vart generert og generer dei med +N+Prop+Attr
-		grep "+N" $generated_lemmas_plnom.$f.txt | sed 's/+N+Prop+Pl+Nom/+N+Prop+Attr/' \
-            | $lookup_tool $generator_file.$suffix \
-		    | cut -f2 > $generated_lemmas_attr.$f.txt
-
-
-###### Collect results: #######
-grep -v "+N" $generated_lemmas_sgnom.$f.txt > $generated_lemmas.$f.txt
-grep -v "+N" $generated_lemmas_plnom.$f.txt >> $generated_lemmas.$f.txt
-grep -v "+N" $generated_lemmas_attr.$f.txt >> $generated_lemmas.$f.txt
-
-
-# Sorter, unifiser dataene som ikke har vært sortert og unifisert
-		LC_ALL=no_NO.UTF-8 sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt
-	    LC_ALL=no_NO.UTF-8 sort -u -o $lemmas $lemmas		
-
-# Sammenlikne: Former som er i lemmalista men ikke i lista med genererte former,
-# lagre i missingProperLemmas.txt. Formene generes med  +N+Prop+Sg+Nom for
-# enklere debugging.
-		LC_ALL=no_NO.UTF-8 comm -23 $lemmas $generated_lemmas.$f.txt | sed 's/$/+N+Prop+Sg+Nom/' \
-		     | $lookup_tool $generator_file.$suffix >> $result_file.$f.txt
-		LC_ALL=no_NO.UTF-8 comm -23 $lemmas $generated_lemmas.$f.txt \
-		     | $lookup_tool $analyser_file.$suffix > $ana_result_file.$f.txt
-
-# Open the diff file in SubEthaEdit (if there is a diff):
-		if [ -s $result_file.$f.txt ]; then
-			# Only open the failed lemmas in see if @SEE@ is defined:
-			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $result_file.$f.txt &
-				#$EXTEDITOR $ana_result_file.$f.txt &
-            # If you don't have see, print a message instead:
-            else
-                echo "There were problem lemmas. Details in:"
-                echo "* $result_file.$f.txt    "
-                echo "* $ana_result_file.$f.txt"
-                head $result_file.$f.txt $ana_result_file.$f.txt
-			fi
-		    Fail=1
-		    echo "$f - FAIL"
-		    continue
-		fi
-	    echo "$f - PASS"
-	fi
-done
-
-# At least one of the Xerox or HFST tests failed:
-if [ "$Fail" = "1" ]; then
-	exit 1
-fi
-
-if [ $transducer_found -eq 0 ]; then
-    echo ERROR: No transducer found $analyser_file $generator_file
-    exit 77
-fi
-
-# When done, remove the generated data file:
-rm -f $lemmas $generated_lemmas.$f.txt $generated_lemmas_attr.$f.txt $generated_lemmas_plnom.$f.txt $generated_lemmas_sgnom.$f.txt
